# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 14:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20180609_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 9, 17, 17, 26, 398242)),
        ),
    ]
