# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 16:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0005_auto_20180609_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='users',
            field=models.ManyToManyField(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 11, 19, 33, 27, 922435)),
        ),
    ]
