# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 17:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_auto_20180614_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 14, 20, 59, 37, 673367)),
        ),
    ]
