# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 16:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0011_auto_20180614_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='period',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday '), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 15, 19, 8, 50, 594194)),
        ),
    ]
