# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 16:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0012_auto_20180615_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='period',
        ),
        migrations.AddField(
            model_name='task',
            name='period_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='period_val',
            field=models.CharField(blank=True, choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly'), ('N', 'None')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 15, 19, 18, 13, 451896)),
        ),
    ]
