# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 16:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0013_auto_20180615_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 15, 19, 19, 22, 18217)),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('O', 'Overdue'), ('C', 'Completed'), ('T', 'Trash')], default='P', max_length=1),
        ),
    ]
