# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 23:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0016_auto_20180616_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 16, 2, 8, 54, 463710)),
        ),
    ]
