# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 10:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0017_auto_20180616_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 16, 13, 3, 6, 712849)),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('0', 'High'), ('1', 'Medium'), ('2', 'Low'), ('-1', 'None')], default='-1', max_length=1),
        ),
    ]
