# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 10:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0018_auto_20180616_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 16, 13, 7, 37, 681216)),
        ),
        migrations.AlterField(
            model_name='task',
            name='repeat_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday '), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=10, null=True),
        ),
    ]
