# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0022_auto_20180624_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(blank=True),
        ),
    ]
